name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  myInput:              # change this
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: "composite"
  steps:
  - uses: actions/setup-go@v4
    with:
      go-version: 1.21
  - run: |
      (
        cd "${{ github.action_path }}"
        out="${{ github.action_path }}/action"
        go build -o "${out}" .
        echo "install-path=${out}" >> "${GITHUB_OUTPUT}"
      )
    id: build
    shell: bash
  - run: |
      echo "${{ toJSON(github) }}"
      ${{ steps.install.build.install-path }}
    shell: bash
    env:
      ACTION_GO_INPUTS: "${{ toJSON(inputs) }}"
