name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  myInput:              # change this
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: "composite"
  steps:
  - run: |
      # This is hacky but we don't have this ref anywhere else
      echo "action-ref=$(basename ${{ github.action_path }})" >> ${GITHUB_OUTPUT}
    id: action-ref
    shell: bash
  - uses: actions-go/go-install@main
    id: install
    with:
      module: "github.com/actions-go/go-action@${{ steps.action-ref.outputs.action-ref != '.' && steps.action-ref.outputs.action-ref || github.sha }}"
  - run: |
      echo "${{ toJSON(github) }}"
      ${{ steps.install.outputs.install-path }}
    shell: bash
    env:
      ACTION_GO_INPUTS: "${{ toJSON(inputs) }}"
