name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  myInput:              # change this
    description: 'input description here'
    default: 'default value if applicable'
outputs:
  time:
    value: ${{ steps.run.outputs.time }}
runs:
  using: "composite"
  steps:
  - id: build-action
    name: Build go action
    uses: actions-go/build@v1
    with:
      action_path: ${{ github.action_path }}
      action: ${{ github.action }}
      go-version: "1.21" # defaults to 1.21
  - name: Run my action
    shell: bash
    id: run
    run: ${{ steps.build-action.outputs.install-path }}
    env:
      ACTION_GO_INPUTS: "${{ toJSON(inputs) }}"
