name: "build-dist"
on: # rebuild any branch changes
  push:
    paths:
      - '*'
      - '**/*'
      - '!dist/**'
    branches-ignore:
      - '*'
    tags-ignore:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.1.5
        with:
          go-version: '1.17'
      - run: go build -v -o dist/main
      - uses: actions/upload-artifact@v3.1.0
        with:
          name: main-${{ matrix.runs-on }}
          path: dist/main
  publish:
    name: Publish new action version
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v2.1.0
        with:
          name: main-ubuntu-latest
          path: main-ubuntu-latest
      - uses: actions/download-artifact@v2.1.0
        with:
          name: main-macos-latest
          path: main-macos-latest
      - uses: actions/download-artifact@v2.1.0
        with:
          name: main-windows-latest
          path: main-windows-latest
      - uses: actions-go/update@v1
